### ISSUE TITLE
how to get soulmeter 

### ISSUE THREAD

**Issue by hdxjfe0802l6** [Cynventria/SoulMeter_keyFile#2]
The original item has been lost

**Comment by Cynventria** [comment]
The original soul meter powered by packet diverting are no longer functionable due to the improvement of game security, after the game being hacked.

Encryption of the data became way more complicated so that we can't gather information from the raw data for now.

I did heard of a version of this application that gathers data straight from the game, but that method may be questionable, and it's not published or maintained by me,  so I don't have further information for you.
